### ISSUE TITLE
not loading .VRM files

### ISSUE THREAD

**Issue by zlobuz** [BSQ-VRM/VRM-Qavatars#5]
so the mod is not recognizing any vrm files on questpatcher and every time i try to drag and drop,it says unrecognized file type .vrm

**Comment by Futuremappermydud** [comment]
Try updating quest patcher.

**Comment by zlobuz** [comment]
it is updated

**Comment by Futuremappermydud** [comment]
If the mod is installed in quest patcher and it's on the latest version then it works

**Comment by zlobuz** [comment]
so i updated it to 2.10 and its alright...sorry im just dumb

**Comment by Futuremappermydud** [comment]
All good
